version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: kazisyeef/node_docker_app
    ports:
      - "3000:3000"  # Corrected port mapping syntax
    environment:
      - PG_DB=node_docker_db
      - PG_USER=kazisyeef
      - PG_PASSWORD=12345
      - PG_HOST=node_db  # Corrected typo
    depends_on:
      - node_db  # Corrected service name
    restart: always

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_docker_db
      - POSTGRES_USER=kazisyeef
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
